<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Canvas painter</title>
        <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    </head>
    <body>
    <nav>
  <div class="nav-wrapper">
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><a href="">what</a></li>
      <li><a href="">why</a></li>
    </ul>
  </div>
</nav>
    <div class="container">
        <h1 class="center-align">PIXL</h1>


        <canvas id="myCanvas" width="96" height="64" style="border:1px solid #d3d3d3;">
        </canvas>

        <script>
            var c = document.getElementById("myCanvas");
            var ctx = c.getContext("2d");
            
            
        </script>


    </div>
    </body>
</html>
