<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <!-- Compiled and minified CSS -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        
        <!-- development version, includes helpful console warnings -->
        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    </head>
    <body>
        <h1>PIXLs</h1>

     <div id="pic"></div>
     <img src="abc.jpg">
     </div>
     <div id="button">
     <input type="submit" value ="go"></input>
     </div>
     
    <div id="app">
        <h1>{{ message }}</h1>
    </div>
    <script type="text/javascript" src="javascript/vue.js"></script>
    <script type="text/javascript" src="js/materialize.min.js"></script>

    </body>
</html>
